apiVersion: v2
name: DRR
description: A Helm chart for DRR
type: application
version: 1.0.1
appVersion: "1.1.0"

dependencies:
  - name: redis-sentinel
    alias: redis
    version: 1.0.0
    condition: redis.enabled
    repository: "file://../redis-sentinel"