/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ClaimStatus = (typeof ClaimStatus)[keyof typeof ClaimStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimStatus = {
  NotStarted: 'NotStarted',
  Draft: 'Draft',
  Submitted: 'Submitted',
  UpdateNeeded: 'UpdateNeeded',
  Approved: 'Approved',
  Skipped: 'Skipped',
} as const;
