/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftConditionRequest } from './draftConditionRequest';
import type { ConditionRequestAllOf } from './conditionRequestAllOf';

export type ConditionRequest = DraftConditionRequest & ConditionRequestAllOf;
