/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { RequestActions } from './requestActions';
import type { RequestStatus } from './requestStatus';

export interface ConditionRequestListItem {
  actions?: RequestActions[];
  /** @nullable */
  conditionId?: string;
  /** @nullable */
  conditionMet?: boolean;
  /** @nullable */
  conditionName?: string;
  /** @nullable */
  dateMet?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  limit?: number;
  status?: RequestStatus;
}
