/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type CostCategory = (typeof CostCategory)[keyof typeof CostCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostCategory = {
  ApprovalsPermitting: 'ApprovalsPermitting',
  Assessment: 'Assessment',
  BylawLandUsePlanning: 'BylawLandUsePlanning',
  Communications: 'Communications',
  ConstructionMaterials: 'ConstructionMaterials',
  Contingency: 'Contingency',
  Design: 'Design',
  FirstNationsEngagement: 'FirstNationsEngagement',
  IncrementalStaffing: 'IncrementalStaffing',
  LandAcquisition: 'LandAcquisition',
  Mapping: 'Mapping',
  MitigationPlanning: 'MitigationPlanning',
  NeighbouringJurisdictions: 'NeighbouringJurisdictions',
  Other: 'Other',
  ProjectAdministration: 'ProjectAdministration',
  ProjectPlanning: 'ProjectPlanning',
  ProponentCommunities: 'ProponentCommunities',
  ShortTermInterest: 'ShortTermInterest',
  TemporaryMitigationSolution: 'TemporaryMitigationSolution',
  Training: 'Training',
} as const;
