/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ReportResult } from './reportResult';
import type { CreateInvoiceResultAllOf } from './createInvoiceResultAllOf';

export type CreateInvoiceResult = ReportResult & CreateInvoiceResultAllOf;
