/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentType = {
  ApprovalLetter: 'ApprovalLetter',
  ConditionApproval: 'ConditionApproval',
  CouncilBoardResolution: 'CouncilBoardResolution',
  ForecastReport: 'ForecastReport',
  Invoice: 'Invoice',
  OtherSupportingDocument: 'OtherSupportingDocument',
  PreliminaryDesign: 'PreliminaryDesign',
  ProgressReport: 'ProgressReport',
  ProjectCompletionLetter: 'ProjectCompletionLetter',
  ProofOfPayment: 'ProofOfPayment',
  SCA: 'SCA',
  SitePlan: 'SitePlan',
} as const;
