/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentType = {
  OtherSupportingDocument: 'OtherSupportingDocument',
  Resolution: 'Resolution',
  PreliminaryDesign: 'PreliminaryDesign',
  SitePlan: 'SitePlan',
  ProgressReport: 'ProgressReport',
  Invoice: 'Invoice',
  ProofOfPayment: 'ProofOfPayment',
  ForecastReport: 'ForecastReport',
  ConditionRequest: 'ConditionRequest',
} as const;
