/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Attachment } from './attachment';
import type { ContactDetails } from './contactDetails';
import type { ForecastItem } from './forecastItem';
import type { ForecastStatus } from './forecastStatus';

export interface DraftForecast {
  /** @nullable */
  attachments?: Attachment[];
  /** @nullable */
  authorizedRepresentative?: ContactDetails;
  /** @nullable */
  dateApproved?: string;
  /** @nullable */
  dateSubmitted?: string;
  /** @nullable */
  forecastItems?: ForecastItem[];
  /** @nullable */
  id?: string;
  /** @nullable */
  originalForecast?: number;
  /** @nullable */
  reportDate?: string;
  /** @nullable */
  status?: ForecastStatus;
  /** @nullable */
  total?: number;
  /** @nullable */
  variance?: number;
  /** @nullable */
  varianceComment?: string;
}
