/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ActiveCondition } from './activeCondition';
import type { ContactDetails } from './contactDetails';
import type { Invoice } from './invoice';
import type { PreviousClaim } from './previousClaim';
import type { InterimProjectType } from './interimProjectType';
import type { ClaimStatus } from './claimStatus';

export interface DraftProjectClaim {
  /** @nullable */
  activeCondition?: ActiveCondition;
  /** @nullable */
  authorizedRepresentative?: ContactDetails;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  claimComment?: string;
  /** @nullable */
  contractNumber?: string;
  /** @nullable */
  dateApproved?: string;
  /** @nullable */
  dateSubmitted?: string;
  /** @nullable */
  haveClaimExpenses?: boolean;
  /** @nullable */
  id?: string;
  /** @nullable */
  invoices?: Invoice[];
  /** @nullable */
  plannedEndDate?: string;
  /** @nullable */
  plannedStartDate?: string;
  /** @nullable */
  previousClaims?: PreviousClaim[];
  /** @nullable */
  previousClaimTotal?: number;
  /** @nullable */
  projectType?: InterimProjectType;
  /** @nullable */
  reportDate?: string;
  /** @nullable */
  reportPeriod?: string;
  /** @nullable */
  status?: ClaimStatus;
  /** @nullable */
  totalClaimed?: number;
  /** @nullable */
  totalProjectAmount?: number;
  /** @nullable */
  upFrontPaymentInterest?: number;
}
