/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactDetails } from './contactDetails';
import type { Invoice } from './invoice';
import type { ClaimStatus } from './claimStatus';

export interface DraftProjectClaim {
  /** @nullable */
  authorizedRepresentative?: ContactDetails;
  /** @nullable */
  claimAmount?: number;
  /** @nullable */
  claimComment?: string;
  /** @nullable */
  contractNumber?: string;
  /** @nullable */
  dateApproved?: string;
  /** @nullable */
  dateSubmitted?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  invoices?: Invoice[];
  /** @nullable */
  reportDate?: string;
  /** @nullable */
  status?: ClaimStatus;
}
