/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Attachment } from './attachment';
import type { DraftProjectClaim } from './draftProjectClaim';
import type { PaymentCondition } from './paymentCondition';
import type { ContactDetails } from './contactDetails';
import type { CostProjectionItem } from './costProjectionItem';
import type { ProjectEvent } from './projectEvent';
import type { DraftForecast } from './draftForecast';
import type { FundingStream } from './fundingStream';
import type { InterimReport } from './interimReport';
import type { ProgramType } from './programType';
import type { DraftProgressReport } from './draftProgressReport';
import type { ReportingScheduleType } from './reportingScheduleType';
import type { ProjectStatus } from './projectStatus';

export interface DrrProject {
  /** @nullable */
  attachments?: Attachment[];
  /** @nullable */
  claims?: DraftProjectClaim[];
  /** @nullable */
  conditions?: PaymentCondition[];
  /** @nullable */
  contacts?: ContactDetails[];
  /** @nullable */
  contractNumber?: string;
  /** @nullable */
  costProjections?: CostProjectionItem[];
  /** @nullable */
  endDate?: string;
  /** @nullable */
  eoiId?: string;
  /** @nullable */
  events?: ProjectEvent[];
  /** @nullable */
  forecast?: DraftForecast[];
  /** @nullable */
  fpId?: string;
  /** @nullable */
  fundingAmount?: number;
  /** @nullable */
  fundingStream?: FundingStream;
  /** @nullable */
  id?: string;
  /** @nullable */
  interimReports?: InterimReport[];
  /** @nullable */
  programType?: ProgramType;
  /** @nullable */
  progressReports?: DraftProgressReport[];
  /** @nullable */
  projectNumber?: string;
  /** @nullable */
  projectTitle?: string;
  /** @nullable */
  proponentName?: string;
  /** @nullable */
  reportingScheduleType?: ReportingScheduleType;
  /** @nullable */
  startDate?: string;
  /** @nullable */
  status?: ProjectStatus;
}
