/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftForecast } from './draftForecast';
import type { ForecastAllOf } from './forecastAllOf';

export type Forecast = DraftForecast & ForecastAllOf;
