/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ForecastItem {
  /** @nullable */
  claimsOnThisReport?: number;
  /** @nullable */
  claimsPaidToDate?: number;
  /** @nullable */
  claimsSubmittedNotPaid?: number;
  /** @nullable */
  fiscalYear?: string;
  /** @nullable */
  forecastAmount?: number;
  /** @nullable */
  id?: string;
  /** @nullable */
  remainingClaims?: number;
  /** @nullable */
  totalProjectedExpenditure?: number;
}
