/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftForecast } from './draftForecast';
import type { PeriodType } from './periodType';
import type { DraftProgressReport } from './draftProgressReport';
import type { DraftProjectClaim } from './draftProjectClaim';
import type { InterimProjectType } from './interimProjectType';
import type { InterimReportStatus } from './interimReportStatus';

export interface InterimReport {
  /** @nullable */
  description?: string;
  /** @nullable */
  dueDate?: string;
  /** @nullable */
  forecast?: DraftForecast;
  /** @nullable */
  id?: string;
  /** @nullable */
  periodType?: PeriodType;
  /** @nullable */
  progressReport?: DraftProgressReport;
  /** @nullable */
  projectClaim?: DraftProjectClaim;
  /** @nullable */
  projectType?: InterimProjectType;
  /** @nullable */
  reportDate?: string;
  /** @nullable */
  status?: InterimReportStatus;
}
