/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { CostCategory } from './costCategory';

export interface Invoice {
  /** @nullable */
  claimAmount?: number;
  /** @nullable */
  costCategory?: CostCategory;
  /** @nullable */
  date?: string;
  /** @nullable */
  description?: string;
  /** @nullable */
  grossAmount?: number;
  /** @nullable */
  id?: string;
  /** @nullable */
  invoiceNumber?: string;
  /** @nullable */
  paymentDate?: string;
  /** @nullable */
  supplierName?: string;
  /** @nullable */
  taxRebate?: number;
  /** @nullable */
  totalGST?: number;
  /** @nullable */
  totalPST?: number;
  /** @nullable */
  workEndDate?: string;
  /** @nullable */
  workStartDate?: string;
}
