/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Attachment } from './attachment';
import type { CostCategory } from './costCategory';

export interface Invoice {
  /** @nullable */
  attachments?: Attachment[];
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  claimAmount?: number;
  /** @nullable */
  costCategory?: CostCategory;
  /** @nullable */
  date?: string;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  description?: string;
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  grossAmount?: number;
  /** @nullable */
  id?: string;
  /** @nullable */
  invoiceNumber?: string;
  /** @nullable */
  name?: string;
  /** @nullable */
  paymentDate?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  supplierName?: string;
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  taxRebate?: number;
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  totalGST?: number;
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  totalPST?: number;
  /** @nullable */
  workEndDate?: string;
  /** @nullable */
  workStartDate?: string;
}
