/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { CostCategory } from './costCategory';

export interface PreviousClaim {
  /** @nullable */
  costCategory?: CostCategory;
  /** @nullable */
  originalEstimate?: number;
  /** @nullable */
  totalForProject?: number;
}
