/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftProgressReport } from './draftProgressReport';
import type { ProgressReportAllOf } from './progressReportAllOf';

export type ProgressReport = DraftProgressReport & ProgressReportAllOf;
