/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectStatus } from './projectStatus';

export interface ProjectListItem {
  /** @nullable */
  endDate?: string;
  /** @nullable */
  fundingAmount?: number;
  /** @nullable */
  id?: string;
  /** @nullable */
  projectTitle?: string;
  /** @nullable */
  startDate?: string;
  /** @nullable */
  status?: ProjectStatus;
}
