/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProjectStatus = (typeof ProjectStatus)[keyof typeof ProjectStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectStatus = {
  NotStarted: 'NotStarted',
  InProgress: 'InProgress',
  Complete: 'Complete',
  Inactive: 'Inactive',
} as const;
