/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftProjectClaim } from './draftProjectClaim';
import type { ProjectClaimAllOf } from './projectClaimAllOf';

export type ProjectClaim = DraftProjectClaim & ProjectClaimAllOf;
