/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type RequestActions =
  (typeof RequestActions)[keyof typeof RequestActions];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestActions = {
  View: 'View',
  Edit: 'Edit',
  Create: 'Create',
} as const;
