/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestStatus = {
  Draft: 'Draft',
  Submitted: 'Submitted',
  Approved: 'Approved',
  UpdateNeeded: 'UpdateNeeded',
} as const;
