kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.env }}-drr-landing-tmp
  labels:
    app: {{ .Values.env }}-{{ .Values.app }}
    role: {{ .Values.role }}
    env: {{ .Values.env }}
spec:  
  host: {{ .Values.env }}-{{ .Values.landingHostTmp }}
  to:
    kind: Service
    name: {{ .Values.env }}-drr-landing
    weight: 100
  port:
    targetPort: 2015-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None