apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-drr-landing
  labels:
    app: {{ .Values.app }}
    role: {{ .Values.role }}
    env: {{ .Values.env }}
    app.kubernetes.io/part-of: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: 2015-tcp
  selector:
    name: {{ .Values.env }}-drr-landing
