name: landing-page Build
on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "drr/src/landing-page/**"
      - .github/workflows/build-landing-page.yml
      - .github/workflows/build-template.yml

  pull_request:
    paths:
      - "drr/src/landing-page/**"
      - .github/workflows/build-landing-page.yml
      - .github/workflows/build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: drr/src/landing-page/src
      IMAGE_FILE: drr/src/landing-page/src/Dockerfile
      IMAGE_NAME: landing-page
      REGISTRY: ${{ secrets.OCP4_REGISTRY }}
      NAMESPACE: ${{ secrets.OCP4_NAMESPACE }}
    secrets:
      REGISTRY_USER: ${{ secrets.OCP4_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.OCP4_PASSWORD }}
