name: landing-page Build
on:
  push:
    branches:
      - master
      - "release/**"
    paths:
      - "drr/src/landing-page/**"
      - .github/workflows/build-landing-page.yml
      - .github/workflows/build-template.yml

  pull_request:
    paths:
      - "drr/src/landing-page/**"
      - .github/workflows/build-landing-page.yml
      - .github/workflows/build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: drr/src/landing-page
      IMAGE_FILE: drr/src/landing-page/src/Dockerfile
      IMAGE_NAME: landing-page
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
