name: drr-portal Build
on:
  push:
    branches:
      - master
      - "release/**"
    paths:
      - "drr/src/API/**"
      - "drr/src/UI/**"
      - .github/workflows/build-drr-portal.yml
      - .github/workflows/build-template.yml

  pull_request:
    paths:
      - "drr/src/API/**"
      - "drr/src/UI/**"
      - .github/workflows/build-drr-portal.yml
      - .github/workflows/build-template.yml

jobs:
  build-api:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT:  drr/src/API
      BUILD_CONTEXT: "shared=./shared/src"
      IMAGE_FILE: drr/src/API/Dockerfile
      IMAGE_NAME: drr-api
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-ui:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: drr/src/UI
      IMAGE_FILE: drr/src/UI/Dockerfile
      IMAGE_NAME: drr-ui
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
